fpath=(~/.zsh/custom_completions $fpath)
# Set up the prompt

export DOTFILES_REPOSITORY_PATH="$HOME/dotfiles"

source ~/.zsh/prompt.zsh

setopt histignorealldups sharehistory

bindkey -e
bindkey '^R' history-incremental-search-backward

source ~/.zsh/globals.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/completions.zsh
source ~/.zsh/os.zsh

source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh

small_fortune

python ~/speed_up_keyboard/keyboard_increase.py
source ~/.zsh/keyboard_speed.zsh
#source ~/update_dotfiles.sh &> /dev/null

function preexec() {
    python "$DOTFILES_REPOSITORY_PATH/has_alias/has_alias.py" "$1"
}

export XDG_CONFIG_HOME="$HOME/.config/"

# export PATH="$HOME/.pyenv/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
fpath=(~/.zsh/custom_completions $fpath)

export TF_CPP_MIN_LOG_LEVEL=2

# daily_kata


# source /opt/ros/kinetic/setup.zsh
# open new tab in current directory
[[ -f /etc/profile.d/vte-2.91.sh ]] && . /etc/profile.d/vte-2.91.sh
