---
- name: i3wm
  apt: name="i3-wm" state=present update_cache=yes
  become: yes

- name: configuration directory
  file: 
    path: "/home/{{ user }}/i3"
    state: directory
    mode: 0755
    owner: "{{ user }}"

- name: i3wm configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ playbook_dir }}/../../i3/config', dest: '/home/{{ user }}/i3/config' }
    - { src: '{{ playbook_dir }}/../../i3/i3status.conf', dest: '/home/{{ user }}/i3/i3status.conf' }
    - { src: '{{ playbook_dir }}/../../i3/i3_layout_start.sh', dest: '/home/{{ user }}/i3/i3_layout_start.sh' }
